---
exp_name: qm8_gpnn
exp_dir: exp/qm8_gpnn
runner: QM8Runner
use_gpu: true
gpus: [0]
# seed: 1234
# seed: 5678
seed: 9012
dataset:
  loader_name: QM8Data
  name: chemistry
  data_path: data/QM8/preprocess
  meta_data_path: data/QM8/QM8_meta.p
  num_atom: 70
  num_bond_type: 6  
model:
  name: GPNN
  num_partition: 3
  num_prop: 10
  num_prop_cluster: 1
  num_prop_cut: 1
  input_dim: 64
  hidden_dim: 128
  update_func: GRU
  output_dim: 16
  msg_func: MLP
  aggregate_type: avg
  num_layer: 1
  loss: MSE
train:
  optimizer: Adam
  lr_decay: 0.1
  lr_decay_steps: [10000]
  num_workers: 8
  max_epoch: 200
  batch_size: 64
  display_iter: 100
  snapshot_epoch: 10000
  valid_epoch: 1
  lr: 1.0e-4
  wd: 0.0e-4
  momentum: 0.9
  shuffle: true
  is_resume: false
  resume_model: None
test:  
  batch_size: 64
  num_workers: 0
  # test_model: exp/qm8_gpnn/GPNN_chemistry_2019-Jan-02-20-37-00_18321/model_snapshot_best.pth
  # test_model: exp/qm8_gpnn/GPNN_chemistry_2019-Jan-02-23-18-03_18654/model_snapshot_best.pth
  test_model: exp/qm8_gpnn/GPNN_chemistry_2019-Jan-02-23-18-20_19110/model_snapshot_best.pth