---
exp_name: qm8_mpnn
exp_dir: exp/qm8_mpnn
runner: QM8Runner
use_gpu: true
gpus: [0]
seed: 1234
dataset:
  loader_name: QM8Data
  name: chemistry
  data_path: data/QM8/preprocess
  meta_data_path: data/QM8/QM8_meta.p
  num_atom: 70
  num_bond_type: 6  
model:
  name: MPNN
  num_prop: 7
  input_dim: 64
  hidden_dim: 128
  update_func: GRU
  output_dim: 16
  # msg_func: embedding
  msg_func: MLP
  num_step_set2vec: 10
  aggregate_type: avg
  num_layer: 1
  loss: MSE
train:
  optimizer: Adam
  lr_decay: 0.1
  lr_decay_steps: [10000]
  num_workers: 4
  max_epoch: 200
  batch_size: 64
  display_iter: 100
  snapshot_epoch: 10000
  valid_epoch: 1
  lr: 1.0e-4
  wd: 0.0e-4
  momentum: 0.9
  shuffle: true
  is_resume: false
  resume_model: None
test:  
  batch_size: 64
  num_workers: 0
  test_model: 
